#!/bin/bash

rm -r wrk1
rm -r wrk2
rm -r wrk3
rm -r wrk4
rm -r wrk5
rm -r wrk6
rm -r wrk7
rm -r wrk8
rm -r wrk9
rm -r wrk10
rm -r wrk11
rm -r wrk12
rm -r wrk13
rm -r wrk14
rm -r wrk15
rm -r wrk16
rm -r wrk17
rm -r wrk18
rm -r wrk19
rm -r wrk20


